CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN;

CREATE TABLE public.mainspring_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_ref TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    customer_email TEXT,
    customer_phone TEXT NOT NULL,
    customer_address TEXT,
    items JSONB NOT NULL,
    subtotal_aed NUMERIC(12, 2) NOT NULL,
    surcharge_pct NUMERIC(5, 2) NOT NULL DEFAULT 0,
    total_aed NUMERIC(12, 2) NOT NULL,
    currency TEXT NOT NULL DEFAULT 'AED',
    payment_method TEXT NOT NULL,
    payment_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (payment_status IN ('pending', 'processing', 'paid', 'failed', 'refunded', 'cancelled')),
    payment_gateway_ref TEXT,
    payment_gateway_response JSONB,
    order_status TEXT NOT NULL DEFAULT 'pending',
    tracking_number TEXT,
    device_type TEXT,
    user_agent TEXT,
    ip_address TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT mainspring_orders_payment_method_check
        CHECK (payment_method IN ('bank_transfer', 'ziina', 'cash_in_store'))
);

CREATE TABLE public.mainspring_order_status_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL REFERENCES public.mainspring_orders(id) ON DELETE CASCADE,
    old_status TEXT,
    new_status TEXT NOT NULL,
    changed_by TEXT NOT NULL DEFAULT 'system',
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.mainspring_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT,
    model TEXT,
    name TEXT,
    reference_code TEXT,
    image_urls TEXT[],
    category TEXT,
    subcategory TEXT,
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    status TEXT NOT NULL DEFAULT 'available',
    sold_at TIMESTAMPTZ,
    sold_price NUMERIC(12, 2),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.mainspring_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous order creation"
    ON public.mainspring_orders FOR INSERT
    WITH CHECK (TRUE);
